"""init_table

Revision ID: 9388957050d0
Revises: 7cc1cacf1542
Create Date: 2025-01-11 15:43:42.550250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9388957050d0'
down_revision: Union[str, None] = '7cc1cacf1542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_config',
    sa.Column('sentiment', sa.String(length=255), nullable=False, comment='情感倾向：正面、负面、中性'),
    sa.Column('topic', sa.String(length=255), nullable=True, comment='主要主题'),
    sa.Column('summary', sa.String(length=255), nullable=False, comment='总结类：对产品的看法、对营销手段的评论、表达向往、表达讽刺、其他'),
    sa.Column('ext_info', sa.Text(), nullable=True, comment='扩展字段，存储其他的 prompt'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统 prompt'),
    sa.Column('user_prompt', sa.Text(), nullable=True, comment='用户 prompt'),
    sa.Column('deleted', sa.Boolean(), nullable=False, comment='逻辑删除标志，0 表示未删除，1 表示已删除'),
    sa.Column('creator', sa.String(length=255), nullable=False, comment='创建人'),
    sa.Column('updater', sa.String(length=255), nullable=False, comment='修改人'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='ID'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_config')
    # ### end Alembic commands ###
