"""init_table

Revision ID: f61242cd4736
Revises: 64088c4020aa
Create Date: 2025-01-11 09:25:47.481283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f61242cd4736'
down_revision: Union[str, None] = '64088c4020aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_id', table_name='content_analytics_info')
    op.drop_table('content_analytics_info')
    op.drop_table('social_media_comment_info')
    op.drop_table('content_creator')
    op.drop_table('users')
    op.drop_index('idx_prompt_config_id', table_name='task_config')
    op.drop_table('task_config')
    op.drop_table('social_media_content_info')
    op.drop_index('idx_comment_id', table_name='comment_analytics_info')
    op.drop_table('comment_analytics_info')
    op.drop_index('fk_comment_sec_uid_', table_name='social_media_comment_list')
    op.drop_index('fk_comment_time_', table_name='social_media_comment_list')
    op.drop_index('fk_comment_uid_', table_name='social_media_comment_list')
    op.drop_index('fk_pk', table_name='social_media_comment_list')
    op.drop_table('social_media_comment_list')
    op.drop_table('prompt_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_config',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='配置的唯一标识符'),
    sa.Column('sentiment', mysql.VARCHAR(length=255), nullable=False, comment='情感倾向：正面、负面、中性'),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True, comment='主要主题'),
    sa.Column('summary', mysql.VARCHAR(length=255), nullable=False, comment='总结类：对产品的看法、对营销手段的评论、表达向往、表达讽刺、其他'),
    sa.Column('system_prompt', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='系统的 prompt'),
    sa.Column('user_prompt', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), nullable=True, comment='用户信息的 prompt'),
    sa.Column('ext_info', mysql.TEXT(), nullable=True, comment='扩展字段，存储其他的 prompt'),
    sa.Column('deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='逻辑删除标志，0 表示未删除，1 表示已删除'),
    sa.Column('create_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='创建人'),
    sa.Column('update_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='修改人'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('social_media_comment_list',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('platform', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True, comment='平台'),
    sa.Column('platform_account_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True, comment='平台账号ID'),
    sa.Column('platform_media_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=200), nullable=True, comment='视频或文章ID'),
    sa.Column('comment_id', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=50), nullable=True, comment='评论ID'),
    sa.Column('comment_content', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=500), nullable=True, comment='评论内容'),
    sa.Column('comment_like', mysql.INTEGER(), autoincrement=False, nullable=True, comment='评论内容点赞数'),
    sa.Column('comment_uid', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=50), nullable=True, comment='评论用户ID'),
    sa.Column('comment_sec_uid', mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=100), nullable=True, comment='评论用户uid'),
    sa.Column('comment_user_nickname', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=200), nullable=True, comment='评论用户昵称'),
    sa.Column('comment_time', mysql.DATETIME(), nullable=True, comment='评论时间'),
    sa.Column('deleted', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('create_by', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='创建者'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.Column('update_by', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('comment_json_extra', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True, comment='json字符串'),
    sa.Column('reply_comment_total', mysql.BIGINT(), autoincrement=False, nullable=True, comment='评论回复数量'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('fk_pk', 'social_media_comment_list', ['platform', 'platform_account_id', 'platform_media_id', 'comment_id'], unique=False)
    op.create_index('fk_comment_uid_', 'social_media_comment_list', ['comment_uid'], unique=False)
    op.create_index('fk_comment_time_', 'social_media_comment_list', ['comment_time'], unique=False)
    op.create_index('fk_comment_sec_uid_', 'social_media_comment_list', ['comment_sec_uid'], unique=False)
    op.create_table('comment_analytics_info',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='评论的唯一标识符'),
    sa.Column('task_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='关联任务 id'),
    sa.Column('comment_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='原始评论数据的 id'),
    sa.Column('content', mysql.TEXT(), nullable=False, comment='评论的内容'),
    sa.Column('sentiment', mysql.VARCHAR(length=255), nullable=False, comment='情感倾向：正面、负面、中性'),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True, comment='主要主题'),
    sa.Column('keywords', mysql.JSON(), nullable=True, comment='关键词'),
    sa.Column('summary', mysql.VARCHAR(length=255), nullable=False, comment='总结��类：对产品的看法、对营销手段的评论、表达向往、表达讽刺、其他'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('create_by', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('update_by', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_comment_id', 'comment_analytics_info', ['comment_id'], unique=False)
    op.create_table('social_media_content_info',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('platform', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True, comment='平台'),
    sa.Column('platform_account_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True, comment='平台账号ID'),
    sa.Column('platform_nickname', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True, comment='平台账号昵称'),
    sa.Column('platform_media_id', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=200), nullable=True, comment='视频或文章ID'),
    sa.Column('title', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True, comment='文章标题'),
    sa.Column('content', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True, comment='文章内容'),
    sa.Column('comments_count', mysql.INTEGER(), autoincrement=False, nullable=True, comment='评论数量'),
    sa.Column('liked_count', mysql.INTEGER(), autoincrement=False, nullable=True, comment='点赞数量、喜欢数量'),
    sa.Column('collected_count', mysql.INTEGER(), autoincrement=False, nullable=True, comment='收藏数量'),
    sa.Column('link', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True, comment='链接地址'),
    sa.Column('pub_time', mysql.DATETIME(), nullable=True, comment='文章发布时间'),
    sa.Column('pub_update_time', mysql.DATETIME(), nullable=True, comment='文章更新时间'),
    sa.Column('deleted', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否删除'),
    sa.Column('create_by', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='创建者'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.Column('update_by', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='修改时间'),
    sa.Column('ext_info', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True, comment='json字符串，原始报文'),
    sa.PrimaryKeyConstraint('id'),
    comment='社交媒体文章记录表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='社交媒体文章记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('task_config',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='任务的唯一标识符'),
    sa.Column('prompt_config_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='评论配置表 id'),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False, comment='任务状态：待处理、处理中、已完成、失败'),
    sa.Column('priority', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='任务优先级，数值越大优先级越高'),
    sa.Column('task_type', mysql.VARCHAR(length=50), nullable=False, comment='任务类型'),
    sa.Column('config_detail', mysql.TEXT(), nullable=True, comment='配置明细'),
    sa.Column('error_message', mysql.TEXT(), nullable=True, comment='错误信息，如果任务失败则记录错误信息'),
    sa.Column('deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='逻辑删除标志，0 表示未删除，1 表示已删除'),
    sa.Column('create_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='创建人'),
    sa.Column('update_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='修改人'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='分析任务表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='分析任务表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_prompt_config_id', 'task_config', ['prompt_config_id'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('content_creator',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='创作者的唯一标识符'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='创作者的姓名'),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False, comment='创作者的电子邮件地址'),
    sa.Column('bio', mysql.TEXT(), nullable=True, comment='创作者的简介'),
    sa.Column('profile_picture', mysql.VARCHAR(length=255), nullable=True, comment='创作者的头像 URL'),
    sa.Column('platform', mysql.VARCHAR(length=255), nullable=False, comment='创作者所属的平台'),
    sa.Column('create_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='逻辑删除标志，0 表示未删除，1 表示已删除'),
    sa.Column('create_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='创建人'),
    sa.Column('update_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='修改人'),
    sa.PrimaryKeyConstraint('id'),
    comment='媒体内容创作者表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='媒体内容创作者表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('social_media_comment_info',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='评论的唯一标识符'),
    sa.Column('content_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='social_media_content_info 表 id，关联的营销内容'),
    sa.Column('parent_comment_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='父评论 ID'),
    sa.Column('reply_to_comment_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='回复的评论 ID'),
    sa.Column('content', mysql.TEXT(), nullable=False, comment='评论内容'),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='用户的唯一标识符'),
    sa.Column('user_username', mysql.VARCHAR(length=255), nullable=True, comment='用户名'),
    sa.Column('user_profile_pic_url', mysql.VARCHAR(length=255), nullable=True, comment='用户头像 URL'),
    sa.Column('platform', mysql.VARCHAR(length=20), nullable=False, comment='评论所在的平台，小红书、tiktok、FB 等'),
    sa.Column('work_link', mysql.VARCHAR(length=255), nullable=False, comment='作品链接'),
    sa.Column('child_comment_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='子评论数量'),
    sa.Column('comment_like_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='评论点赞数'),
    sa.Column('has_liked_comment', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否点赞评论'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='评论创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='评论更新时间'),
    sa.PrimaryKeyConstraint('id', 'content_id', 'parent_comment_id', 'reply_to_comment_id', 'user_id'),
    comment='媒体评论信息表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='媒体评论信息表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('content_analytics_info',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='评论的唯一标识符'),
    sa.Column('task_id', mysql.BIGINT(), autoincrement=False, nullable=True, comment='关联任务 id'),
    sa.Column('content', mysql.TEXT(), nullable=False, comment='评论的内容'),
    sa.Column('sentiment', mysql.VARCHAR(length=255), nullable=False, comment='情感倾向：正面、负面、中性'),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True, comment='主要主题'),
    sa.Column('keywords', mysql.VARCHAR(length=255), nullable=True, comment='关键词'),
    sa.Column('summary', mysql.VARCHAR(length=255), nullable=False, comment='总结��类：对产品的看法、对营销手段的评论、表达向往、表达讽刺、其他'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='逻辑删除标志，0 表示未删除，1 表示已删除'),
    sa.Column('create_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='创建人'),
    sa.Column('update_by', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='修改人'),
    sa.PrimaryKeyConstraint('id'),
    comment='营销内容分析结果表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='营销内容分析结果表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_task_id', 'content_analytics_info', ['task_id'], unique=False)
    # ### end Alembic commands ###
